### ISSUE TITLE
Generating patches for training

### ISSUE THREAD

**Issue by Sahardastani** [abhisheksambyal/Self-supervised-learning-by-context-prediction#1]
Hello,

Thank you for sharing this repository. 
In `MyDataset` class, why did you define `validate`? Because I can't see the difference here when we have `validate` and when we have not:

`if validate:
  self.train_data = df.values
else:
  self.train_data = df.values`

**Comment by abhisheksambyal** [comment]
Hi,
Thanks for pointing it out.
It is an unnecessary code. You can just keep `self.train_data = df.values`.
